version: '3.8'

services:
  auth:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres://postgres:password@db:5432/auth_db?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
